<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <joint name="laser_joint" type="fixed">
    <parent link="base_link"/>
    <child link ="laser_frame"/>
    <origin xyz="0 0 ${base_height + lidar_length}"/>
  </joint>

  <link name="laser_frame">
    <visual name="laser_visual">
      <geometry>
          <cylinder length="${lidar_length}" radius="${lidar_radius}" />
      </geometry>
      <material name="blue"/>
      <!-- <material>
        <ambient>1 0 0 1</ambient>
        <diffuse>1 0 0 1</diffuse>
      </material> -->
    </visual>

    <collision name="laser_collision">
      <geometry>
          <cylinder length="${lidar_length}" radius="${lidar_radius}" />
      </geometry>
    </collision>
    
    <xacro:inertial_cylinder mass="0.1" length="0.05" radius="0.05">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_cylinder>

  </link>

<gazebo reference="laser_frame">
  <sensor name="laser" type="gpu_lidar">
    <pose>0 0 0 0 0 0</pose>
    <update_rate>10</update_rate>
    <visualize>true</visualize>
    <lidar>
      <scan>
        <horizontal>
          <samples>360</samples>
          <min_angle>-3.14</min_angle>
          <max_angle>3.14</max_angle>
        </horizontal>
      </scan>
      <range>
        <min>0.3</min>
        <max>12.0</max>
      </range>
    </lidar>

    <topic>scan</topic>
    <gz_frame_id>laser_frame</gz_frame_id>

  </sensor>
</gazebo>


</robot>