<?xml version="1.0"?>

<robot name="orion" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find orion_description)/urdf/robot_properties.urdf.xacro"/>
<xacro:include filename="$(find orion_description)/urdf/diff_wheels.urdf.xacro"/>
<xacro:include filename="$(find orion_description)/urdf/inertial_macros.xacro" />
<!-- <xacro:include filename="$(find orion_description)/urdf/ros2_control.xacro" /> -->

<!-- Robot Base -->
<link name="base_link"> </link>

<joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="-0.1 0 0"/>
</joint>

<!-- Base Chassis -->
<link name="chassis">
    <visual>
        <origin xyz="${base_height} 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="white"/>
    </visual>

    <collision>
        <origin xyz="${base_height} 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
    </collision>

    <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
      <origin xyz="${base_height} 0 ${base_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
</link>

<!-- Diff Wheels -->
<xacro:wheel prefix="left" reflect="1" />
<xacro:wheel prefix="right" reflect="-1" />

<!-- Caster Wheels -->
<joint name="caster_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
    <origin xyz="0.24 0 0" rpy="0 0 0"/>
</joint>

 <link name="caster_wheel">
        <visual>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <geometry>
                <sphere radius="${caster_wheel_radius}"/>
            </geometry>
        </collision>
        <xacro:inertial_sphere mass="10" radius="${caster_wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_sphere>
    </link>

    <gazebo reference="caster_wheel">
        <material>Gazebo/Blue</material>
        <mu1 value="0.01"/>
        <mu2 value="0.01"/>
    </gazebo>

</robot>