<?xml version="1.0"?>

<robot name="orion" xmlns:xacro="http://www.ros.org/wiki/xacro">

<xacro:include filename="$(find orion_simulation)/description/urdf/robot_properties.urdf.xacro"/>
<xacro:include filename="$(find orion_simulation)/description/urdf/diff_wheels.urdf.xacro"/>
<xacro:include filename="$(find orion_simulation)/description/urdf/inertial_macros.xacro" />

<!-- Robot Base -->
<link name="base_link"> </link>

<joint name="chassis_joint" type="fixed">
    <parent link="base_link"/>
    <child link="chassis"/>
    <origin xyz="-0.1 0 0"/>
</joint>

<link name="chassis">
    <visual>
        <origin xyz="${base_height} 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
        <material name="white"/>
    </visual>

    <collision>
        <origin xyz="${base_height} 0 ${base_height/2}" rpy="0 0 0"/>
        <geometry>
            <box size="${base_length} ${base_width} ${base_height}"/>
        </geometry>
    </collision>

    <xacro:inertial_box mass="0.5" x="0.3" y="0.3" z="0.15">
      <origin xyz="${base_height} 0 ${base_height/2}" rpy="0 0 0"/>
    </xacro:inertial_box>
</link>

<!-- LEFT WHEEL -->


<xacro:wheel prefix="left" reflect="1" />
<xacro:wheel prefix="right" reflect="-1" />


<joint name="caster_wheel_joint" type="fixed">
    <parent link="chassis"/>
    <child link="caster_wheel"/>
    <origin xyz="0.24 0 0" rpy="0 0 0"/>
</joint>

<link name="caster_wheel">
    <visual>
        <geometry>
            <sphere radius="0.05" />
        </geometry>
        <material name="black"/>
    </visual>

    <xacro:inertial_sphere mass="0.1" radius="0.05">
      <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:inertial_sphere>
</link>

</robot>